### ISSUE TITLE
Simple: All resource specifications require names

### ISSUE THREAD

**Issue by Kriechi** [inkblot/puppet-shorewall#11]
I'm getting the following error:
```
Puppet (err): All resource specifications require names; expected '%s' at ...
```
https://github.com/inkblot/puppet-shorewall/blob/master/manifests/simple.pp#L41

What am I missing?
Shouldn't that code look something like:

```
  shorewall::port { 'port-ping-accept':
    application => 'Ping',
    action      => 'ACCEPT',
  }
```

**Comment by inkblot** [comment]
I'll spin up a VM and see what I get. I haven't used the shorewall::simple class in some time, so it's possible that its development has fallen behind other parts of the module. Is there anything I should do beyond `include shorewall::simple` in order to repeat your experience?

**Comment by inkblot** [comment]
Oh, nevermind, I see what you did there.

**Comment by Kriechi** [comment]
Thanks.
