### ISSUE TITLE
Support: routestopped

### ISSUE THREAD

**Issue by Kriechi** [inkblot/puppet-shorewall#13]
I could not find any commands to create a `routestopped` file.
Do I have to do it manually or is there some trick involved?

My gateway uses `routestopped` to whitelist the next hop in my gateway chain.

routestopped (which seems to be deprecated in favor of `stoppedrules`):
http://www.shorewall.net/manpages/shorewall-routestopped.html

stoppedrules:
http://www.shorewall.net/manpages/shorewall-stoppedrules.html

**Comment by inkblot** [comment]
Any file that the module doesn't specifically handle you can manage manually. If you like I could add support for it.

**Comment by inkblot** [comment]
I've written some code to support `routestopped`. I have not yet tried to run it anywhere, and so it may have some errors, but it's structurally similar to other features of the module. I also haven't tried to support `stoppedrules` with this change. I'll put the changes in a pull request. If you could please, let me know whether they meet your needs. I'll try them out somewhere, too, when I get a chance.
