### ISSUE TITLE
Expose blacklist options

### ISSUE THREAD

**Issue by greenaar** [inkblot/puppet-shorewall#15]
Per http://shorewall.net/blacklisting_support.htm -- could you make the option selectable, vs just enforcing DROP?

This would help in cases where you want to bulk whitelist an IP against a range of ports.

**Comment by greenaar** [comment]
Actually, being able to specify source and dest as well would finish up the feature set, especially if port was an array instead of a string.

**Comment by inkblot** [comment]
> could you make the option selectable, vs just enforcing DROP?

What option do you mean? Can you provide an example usage of the module that illustrates what you would like to do and describe the effect you would like it to have?

**Comment by greenaar** [comment]
absolutely.

blacklist.pp

define shorewall::blacklist (
    $action        = 'DROP',
    $type          = 'ipv4',
    $source        = 'all',
    $address       = 'all',
    $dest          = '$FW',
    $proto         = '',
    $port          = [],
    $order         = '50',
) {

blacklist.erb
<%= @address %>     <%= @proto %>    <%= @port.empty? ? '' : " #{Array(@port).join(',')}" %>

blrules.erb
<%= @action %>    <%= source %>:<%= @address %>     <%= @dest %>   <%= @proto %>    <%= @port.empty? ? '' : " #{Array(@port).join(',')}" %>

Relatively small changes, working successfully in my environment.

This lets me select not only a range of ports, but also to use the whitelist option (to blacklist globally with an exclusion, for example if i needed to expose 22, but just to one or more destinations)

**Comment by inkblot** [comment]
Oh, you've got working code! Could you just submit it as a pull request?

**Comment by greenaar** [comment]
https://github.com/inkblot/puppet-shorewall/pull/17 -- how's that?

**Comment by inkblot** [comment]
Great, let's keep the rest of the thread going there.
